description: "This is a test of the promptfoo library"

prompts:
  # Prompt 1
  - id: prompt1
    prompt:
      'Write few sentences about Rafa Nadal'
  # Prompt 2
  - id: prompt2
    prompt:
      'Summarize the content from Prompt1: {{output_from_prompt1}} in {{language}}'
  
  

providers:
  - id: openai:chat:gpt-4o
    config:
      apiKey: {{process.env.OPENAI_API_KEY}}
  
tests:
  - vars:
      language: Polish
    steps:
      - id: step1
        prompt_id: prompt1
      - id: step2
        prompt_id: prompt2
        vars:
          output_from_prompt1: {{step1.output}}
  


  

